services:
  zigbee2mqtt-health:
    image: ghcr.io/sheyabernstein/zigbee2mqtt-health:latest
    container_name: zigbee2mqtt-health
    restart: unless-stopped
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      MQTT_BROKER: localhost
      MQTT_PORT: 1883
      MQTT_USERNAME: user
      MQTT_PASSWORD: password
